{
  config,
  pkgs,
  ...
}:
let
  pins = import ../../npins;
  user = "alice";

in
{

  nix.nixPath = [
    "nixos-system=${config.users.users.${config.nixith.user}.home}/nixos-config/hosts/wsl/system.nix:"
  ];
  imports = [
    (import pins.NixOS-WSL).outputs.nixosModules.default
    ./hardware-configuration.nix # import important autogenerated stuff
    ../modules/console.nix
    #../modules/run0.nix #NOTE: pam currently doesn't work in WSL, see https://github.com/microsoft/WSL/issues/9213
    ../common/desktop.nix
    ../common/system.nix
    ../common/security.nix
    ../common/yubikey.nix
    ../module.nix
    ../modules/networkd.nix
    ../modules/stylix.nix
    ../common/virtualisation.nix
    #"${pins.disko}/module.nix"
    "${pins.home-manager}/nixos"
    (
      { config, ... }:
      {
        home-manager = {
          backupFileExtension = "backup";
          useGlobalPkgs = true;
          users.${user} = import ./wsl-home.nix {
            inherit
              user
              pkgs
              ;
          };
        };
      }
    )

    {
      nix.registry.nixpkgs.to = {
        type = "path";
        path = pins.nixpkgs;
      };

      nix.channel.enable = false;
      nix.nixPath = [ "nixpkgs=${pins.nixpkgs}:" ];
    }
    {
      nixpkgs.overlays = [
        (import (pins.nixivim)).overlays.default
      ];
    }
    (
      { pkgs, ... }:
      {
        nixpkgs.overlays = [
          (final: prev: {
            inherit (prev.lixPackageSets.stable)
              nixpkgs-review
              nix-eval-jobs
              nix-fast-build
              colmena
              ;
          })
        ];

        nix.package = pkgs.lixPackageSets.stable.lix;
      }
    )
    "${pins.nix-index-database}/nixos-module.nix"
    {
      programs.nix-index-database.comma.enable = true;
      programs.command-not-found.enable = false;
    }
  ];

  nixpkgs.config.allowUnfree = true;

  programs.nh = {
    enable = true;
    clean.enable = true;
    clean.extraArgs = "--keep 5 --keep-since 5d";
  };

  environment.systemPackages = with pkgs; [
    # To manage the actual user configuration
    cachix
    git
    jujutsu
    npins
  ];

  wsl = {
    enable = true;
    interop.register = true;
    useWindowsDriver = true;
    defaultUser = "alice";

  };
  hardware = {
    #hardware acceleration
    graphics = {
      enable = true;
      # extraPackages = with pkgs; [
      #   vpl-gpu-rt
      #   vaapiIntel
      #   # intel-vaapi-driver
      #   # intel-media-driver
      # ];
    };
    enableRedistributableFirmware = true;
  };

  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  networking = {
    hostName = "wsl"; # Define your hostname.
  };
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Enable networking

  # Set your time zone.

  # Enable touchpad support (enabled default in most desktopManager).
  # services.xserver.libinput.enable = true;

  # Power Management
  # powerManagement = {
  #   enable = true;
  #   powertop.enable = true;
  #   cpuFreqGovernor = "ondemand";
  # };
  # environment.sessionVariables = {
  #   LIBVA_DRIVER_NAME = "iHD";
  # }; # Force intel-media-driver

  programs.dconf.enable = true;

  # ZRAM
  zramSwap.enable = true;
  # Define a user account. Don't forget to set a password with ‘passwd’.

  # Allow unfree packages

  # List packages installed in system profile. To search, run:
  # $ nix search wget

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:
  # Enable the OpenSSH daemon.
  services.openssh.enable = true;
  services.tlp.enable = pkgs.lib.mkForce false;
  services.tuned = {
    ppdSettings = {
      main.default = "balanced";
      profiles = {
        balanced = "balanced-battery";
        performance = "throughput-performance";
        power-saver = "laptop-battery-powersave";
      };
    };
    enable = true;
    settings = {
      dynamic_tuning = true;
      recommend_command = true;
    };
  };

  system = {
    stateVersion = "22.11";
  };
}
