{
  config,
  pkgs,
  ...
}:
let
  pins = import ../../npins;

in
{

  nix.nixPath = [
    "nixos-system=${
      config.users.users.${config.nixith.user}.home
    }/nixos-config/hosts/laptop/system.nix:"
  ];
  imports = [
    ./hardware-configuration.nix # import important autogenerated stuff
    ./disko.nix
    ../modules/iwd.nix
    ../modules/networkd.nix
    ../default.nix
    "${pins.disko}/module.nix"
    "${pins.nixos-hardware}/framework/13-inch/12th-gen-intel/"
  ];
  hardware = {

    fw-fanctrl = {
      enable = true;
    };
    flipperzero.enable = true;

    #hardware acceleration
    graphics = {
      enable = true;
      # extraPackages = with pkgs; [
      #   vpl-gpu-rt
      #   vaapiIntel
      #   # intel-vaapi-driver
      #   # intel-media-driver
      # ];
    };

    bluetooth = {
      enable = true;
    };
    enableRedistributableFirmware = true;
  };

  nixith.run0.enable = true;
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  boot = {
    # initrd.kernelModules = [ "xe" ];
    kernelPackages = pkgs.linuxPackages_latest;

    loader.efi = {
      canTouchEfiVariables = true;
      efiSysMountPoint = "/boot/";
    };

    loader.grub = {
      enable = false;
      device = "nodev";
      efiSupport = true;
      useOSProber = true; # enables dual boot;
    };

    loader.systemd-boot = {
      enable = true;
    };
  };

  networking = {
    hostName = "laptop"; # Define your hostname.
    networkmanager = {
      wifi.powersave = true;
    };
  };
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Enable networking

  # Set your time zone.

  # Enable touchpad support (enabled default in most desktopManager).
  # services.xserver.libinput.enable = true;

  # Power Management
  powerManagement = {
    enable = true;
    powertop.enable = true;
    cpuFreqGovernor = "ondemand";
  };
  # environment.sessionVariables = {
  #   LIBVA_DRIVER_NAME = "iHD";
  # }; # Force intel-media-driver
  programs.steam = {
    extraCompatPackages = with pkgs; [ proton-ge-bin ];
    package = pkgs.steam.override {
      extraEnv = {
        RADV_TEX_ANISO = 16;
      };
      extraLibraries =
        pkgs: with pkgs; [
          vulkan-tools
          bubblewrap
          mangohud
          gamemode
          libXcursor
          libXi
          libXinerama
          libXScrnSaver
          libpng
          pipewire
          libpulseaudio
          libvorbis
          stdenv.cc.cc.lib
          libkrb5
          keyutils
        ];
    };
    #extest.enable = true;
    enable = true;
    gamescopeSession = {
      enable = true;
      # env = gamescopeEnv;
      # args = gamescopeArgs;
    };
  };

  programs.dconf.enable = true;

  #Distrobox

  # ZRAM
  zramSwap.enable = true;
  # Define a user account. Don't forget to set a password with ‘passwd’.

  # Allow unfree packages

  # List packages installed in system profile. To search, run:
  # $ nix search wget

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:
  # Enable the OpenSSH daemon.
  services.openssh.enable = true;
  services.tlp.enable = pkgs.lib.mkForce false;
  services.tuned = {
    ppdSettings = {
      main.default = "balanced";
      profiles = {
        balanced = "balanced-battery";
        performance = "throughput-performance";
        power-saver = "laptop-battery-powersave";
      };
    };
    enable = true;
    settings = {
      dynamic_tuning = true;
      recommend_command = true;
    };
  };

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  #  system.stateVersion = "22.11"; # Did you read the comment?
  system = {
    stateVersion = "22.11";
  };
}
