name: "build & cache"
on:
  push:
jobs:
  # check:
  #   runs-on: nix
  #   steps:
  #   - name: nix conf
  #     run: |
  #       echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  #       echo "extra-experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  #   - name: setup CI env
  #     run: |
  #         nix profile install nixpkgs#nodejs_20
  #   - uses: https://code.forgejo.org/actions/checkout@v4
  #
  #   # setup ssh key
  #   - name: attic setup
  #     run: |
  #       nix profile install nixpkgs#attic-client
  #       attic login wonderland http://cache.wonderland:8080 ${{ secrets.ATTIC_KEY }}
  #       attic use server
  #   - run: |
  #       nix flake check --accept-flake-config

  build:
    # needs: check
    runs-on: nix
    strategy: 
      matrix:
      system: [desktop, laptop]
    steps:
    - name: nix conf
      run: echo  ${{ format(.#nixosConfigurations.{0}.config.system.build.toplevel --accept-flake-config, matrix.system) }}
      run: |
        echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
        echo "extra-experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - name: setup CI env
      run: |
          nix profile install nixpkgs#nodejs_20
    - uses: https://code.forgejo.org/actions/checkout@v4

    # setup ssh key
    - name: attic setup
      run: |
        nix profile install nixpkgs#attic-client
        attic login wonderland http://cache.wonderland:8080 ${{ secrets.ATTIC_KEY }}
        attic use server

    - run: |
        format( string, replaceValue0, replaceValue1, ..., replaceValueN)
        # nix build .#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel --accept-flake-config
        nix build ${{ format(.#nixosConfigurations.{0}.config.system.build.toplevel --accept-flake-config, matrix.system) }}
    - run: |
        attic push server ./result
