name: "build & cache"
on:
  push:
jobs:
  check:
    runs-on: nix
    steps:
    - name: nix conf
      run: |
        echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
        echo "extra-experimental-features = nix-command flakes" >> /etc/nix/nix.conf
    - name: setup CI env
      run: |
          nix profile install nixpkgs#nodejs_20
    - uses: https://code.forgejo.org/actions/checkout@v4

    # setup ssh key
    - name: attic setup
      run: |
        nix profile install nixpkgs#attic-client
        attic login wonderland http://cache.wonderland:8080 ${{ secrets.ATTIC_KEY }}
        attic use server
        attic watch-store server &
    - run: |
        nix flake check --accept-flake-config

  build:
    needs: check
    runs-on: nix
    strategy: 
      matrix:
        system:
          - name: desktop
          - name: laptop
    steps:
    - name: nix conf
      run: |
        echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
        echo "extra-experimental-features = nix-command flakes" >> /etc/nix/nix.conf
        echo "substituters = http://cache.wonderland:8080/server https://cache.nixos.org https://nix-community.cachix.org" >> /etc/nix/nix.conf
        echo "trusted-public-keys = server:aQY62nTlvGeHgStgJmVO2FG8+zWHyuld6lC+n+VPx3M= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" >> /etc/nix/nix.conf
    - name: setup CI env
      run: |
          nix profile install nixpkgs#nodejs_20
    - uses: https://code.forgejo.org/actions/checkout@v4

    # setup ssh key
    - name: attic setup
      run: |
        nix profile install nixpkgs#attic-client
        attic login wonderland http://cache.wonderland:8080 ${{ secrets.ATTIC_KEY }}
        attic use server
    - run: |
        nix build .#nixosConfigurations.${{ matrix.system.name }}.config.system.build.toplevel --accept-flake-config
    - run: |
        attic push server ./result
