#!/usr/bin/env dash
clamp() {
	min=$1
	max=$2
	val=$3
	python -c "print(max($min, min($val, $max)))"
}

direction=$1
current=$2

case $direction in

down)
	target=$(clamp 1 10 $(($current + 1)))
	echo "jumping to $target"
	hyprctl dispatch workspace "$target"
	;;

up)
	target=$(clamp 1 10 $(($current - 1)))
	echo "jumping to $target"
	hyprctl dispatch workspace "$target"
	;;

esac
