#!/usr/bin/env dash

spaces() {
	MONITOR_ID_DICT=$(hyprctl monitors -j | jaq --color never -c 'map({key: .name, value: .id}) | from_entries')
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jaq --color never -c --arg table $MONITOR_ID_DICT 'map({key: .id | tostring, value: ({windows: .windows, monitor: .monitor })}) | from_entries | ($table | fromjson) as $jsontable | .[].monitor |=  $jsontable[.]')
	seq 1 10 | jaq --arg windows "$WORKSPACE_WINDOWS" --slurp --color never -c 'map(tostring) | ($windows | fromjson) as $JSONwindows | map({id: ., stats: ($JSONwindows[.]//0)})'
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r line; do
	spaces
done
