#!/usr/bin/env dash

MONITOR_ID_DICT=$(hyprctl monitors -j | jaq -Mc 'map({key: .name, value: .id}) | from_entries')

spaces() {
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jaq -Mc --argjson table $MONITOR_ID_DICT 'map({key: .id | tostring, value: ({windows: .windows, monitor: .monitor })}) | from_entries | .[].monitor |= $table[.]')
	seq 1 10 | jaq --argjson windows "$WORKSPACE_WINDOWS" --slurp -Mc 'map(tostring) | map({id: ., stats: ($windows[.]//0)})'
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r line; do
	spaces
done
