mopidy_spotify: ENC[AES256_GCM,data:NScVm2n0dMrxQMXqHf3u+q3CU0XIC+UTFP1sXwH5MdGZmDXJ+uc/TzXZ5R/ZsOjl/MU3UK7e3z4iPyvPShNzHMOb6WI9TIdgrPSRp9+XdHydb7RacTGbjEvISq4w0w39Ti0c5xzFS2DORZKfveD0AV3FP9FSLJs=,iv:q8PElg7ms6tr1wKAdNMLyiVdmIWiuE27VuYnf+lU99w=,tag:yGjLqz4nWsg8XG3Yq0y6ig==,type:str]
#ENC[AES256_GCM,data:ND1rlmI=,iv:yVVJ5BXfw8yKMVHOmfJoYJ367+MXQFdehyDTyn2jvmM=,tag:ta/w/8EGxpOgcvpLctqlYQ==,type:comment]
mopidy_jellyfin: ENC[AES256_GCM,data:oydqgfp5fWkHe+QXRbXm7QH66gufBnw5HKypHXbGkx0si8mhn/V52ehUhRVHxR7rOi+nDLHAz+g5XVdUzCxQ22ChEEnW3wZb5GEH24f1z4VEOPpqxLC1St/lAu4gVpp0EgnN0l+DgTPfAQjn6UH3shI+CNl3J9X58iKcfKvEVfAcFY3ZPjcBmaDthdiVKMu0LD+hZOXs/X4djjSsPqm5JUii0sU9shImX11PMbBi9iVVebCgnOR2w/0eE72jAjo5uzqSsb8yYu4AH2OJQL/RrTUbCtqZnlYIc8nDwexFk2DiR/hhTLsslZNQib3vl0bTiHHAzXqo2EDYrD7F8yPQ05Z51lFwv3Wnmni7wdodnvIIMvDkCIMs6S+GhEqH8XoCWRnyh1baEuzSLccSD/tG72YEq0WlJN7TBs0t3wjI+YSsdIunM12RhxaoC+U9tqsvxOXjRQ9TodnWeB708tfHXRkWRRWQv4eMsTtFGjPoqzZWjSdGzy2+rNM03WxyEZm4oJ1rgCIMaa9Lvqs5atRs77iy1yEdvzY5zzo8zAvnskbvk3RcxrEpF6FzxRQVRX/FNPd/YgbfGa3Dxj1Yh/XSZ05r6HrrLMpRnH52i5Ax0qEDqN3nriKK1eLmfiz4pmrcOZxnqlxq9D6Cbpd0bXpsiE3C0YLefMKFkmOewFIZT2RzVm8dBvpNY6uNTip9grKJJhxPJAPghYYRBljMGVsJ2OKGh1Zjq356VD1Fxi7QUGN6q0LU6l/h/UG1Xqzakshe2Q==,iv:JgZOhip7GEdXk0LSlhVlTObzkWVkmyI1NSfVDfe2fj4=,tag:+ZpvHtOz+2cfHkwBNMwg6g==,type:str]
sops:
    age:
        - recipient: age1p86gh0rp6xjku5tqcvn6hadhdfqunw7dkhr90csevjdrk9vexakqa4l6q6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZVhkOEU1Q3JGZTJKNkU1
            czNzVkdZZWdFNzZHSGt2eFBKUWJoV0ZSY0VrClhaRTUyZk5hSWFwczd1MXJkN2hK
            R01naGY0d3BTalJRVjZWZkUxK0FnaG8KLS0tIHVGYmphVGR6SG9XS2VIWUs1b1FX
            Mngzbjk5NW10WUFBVWtlYWkwMGYvd3cKS+qhFsoTDertg6utjeIv0JDC69OHRf86
            fEX0JRmJUnKLvucKy4hqY8K1xXSKtbWieUARqySg46DulAvqmyOC+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zswlplhkdu0pzx08uruxwq7lgumvtahrnllcs34xpuxru9xqy3aqtjrkhv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcFg3UzhxZm9JeU85SDZj
            NzBNNTgvdUY4bXRFZTMyd05icjFrRm5iNEVrCngyK0c2a1p4d2ZjWDNnbnFsSDk5
            b3lwU1MxaE5qOTJhT0x3ZGNPMkhyR0UKLS0tIEhRYTVBVzlhTHFUcXhQemdmQTNa
            M2xaVWJ4Y2FIU3I0ckNsWEtuamd5a2MKkX8SlurVq8f/sZ7vUYciTdgn+H3a+qIs
            j/oWrXe48BrADH7dha2T2gzFxSgpxLIMlC9EAuLSDlIvAbvAhAmEAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-11T16:09:39Z"
    mac: ENC[AES256_GCM,data:BtMx/kPItO5niKbzz/T9Ul1ZB3F6Z7qeNtzPtL1ZyskfIwxzaRbna19zX4r9JT+ipz1uSNOd+X23l2f2Zxktq4oJqE9d/vn/gy9drLwoyyRJJ9+8MPUWNxPIbabDioV1J4CDqPKttY2K2TGYtnIguNtt04D+mBLu0IMh/KodIkY=,iv:6/cz/1clWDd/KWhYKApuNkYRWk2nPqS1uPBPCucPZhw=,tag:r+kLuw6GQhRhOuUoWSxxIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
